In [2]:
import numpy as np


# === WARM-UP ===

# 1. Create an array of numbers from 1 to 20
# Expected result: [1, 2, 3, ..., 20]

# 2. Create an array of 15 random integers from 0 to 100
# Hint: np.random.randint

# 3. Find for this array: mean, median, min, max, standard deviation

# 4. Sort the array in ascending order

# 5. Print only elements greater than 50


# === HARDER ===

# 6. Create a 4x4 matrix of random numbers from 0 to 10
# Find: total sum of the matrix, sum by rows, sum by columns

# 7. In the array from task #2, replace all even numbers with 0, keep odd numbers

# 8. Create two arrays: [1,2,3,4,5] and [10,20,30,40,50]
# Calculate: element-wise multiplication, dot product

# 9. Create an array of 100 numbers evenly spaced from 0 to 10
# Hint: np.linspace

# 10. In the array from task #2, find how many numbers fall within the range [20, 80]

In [7]:
np.arange(1,21) # creates an array from 1 to 20 inclusive

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
arr = np.random.randint(0, 101, 15) # creates an array of 15 random integer from 0 to 100
arr

array([ 3, 60, 81, 24, 70, 80, 26, 20,  3, 67, 62, 53, 74, 97, 28])

In [18]:
np.mean(arr)
np.median(arr)
np.min(arr)

np.int64(3)

In [19]:
np.sort(arr) #sorting in ascending order

array([ 3,  3, 20, 24, 26, 28, 53, 60, 62, 67, 70, 74, 80, 81, 97])

In [22]:
np.sort(arr)[::-1] #sorting in descending order

array([97, 81, 80, 74, 70, 67, 62, 60, 53, 28, 26, 24, 20,  3,  3])

In [23]:
arr[arr>50] #sorting by condition and prinint arrays values not booelaean ones

array([60, 81, 70, 80, 67, 62, 53, 74, 97])

In [24]:
arr

array([ 3, 60, 81, 24, 70, 80, 26, 20,  3, 67, 62, 53, 74, 97, 28])

In [25]:
matrix = np.random.randint(0, 11, (4,4))
matrix

array([[ 3, 10,  2,  6],
       [ 1,  8,  7,  1],
       [ 6,  4,  5,  7],
       [ 5,  2,  3,  7]])

In [26]:
np.sum(matrix)

np.int64(77)

In [36]:
np.sum(matrix, axis=0)

array([15, 24, 17, 21])

In [46]:
arr = np.random.randint(0, 11, 15)
arr

array([4, 8, 4, 3, 2, 6, 7, 5, 2, 9, 1, 3, 9, 1, 6])

In [44]:
arr[arr % 2 != 0]

array([7, 9, 7, 3, 7, 5, 7])

In [49]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
arr1
arr2

array([10, 20, 30, 40, 50])

In [50]:
print(arr1 * arr2)

[ 10  40  90 160 250]


In [51]:
print(np.dot(arr1, arr2))

550


In [56]:
arr = np.random.randint(0, 101, 15)

In [60]:
len(arr[(20<=arr) & (arr<=80)])

7

In [61]:
np.sum((arr >= 20) & (arr <= 80))

np.int64(7)

In [63]:
arr = np.linspace(1, 11, 5)
arr

array([ 1. ,  3.5,  6. ,  8.5, 11. ])